# Generated by Django 3.2.5 on 2021-07-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_certificate_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
