# Generated by Django 3.2.5 on 2021-07-26 20:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic_app', '0004_auto_20210726_2349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ClinicalStaff',
        ),
        migrations.RenameField(
            model_name='clinicalstaff',
            old_name='user',
            new_name='staff',
        ),
    ]
