# Generated by Django 3.2.5 on 2021-07-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0005_auto_20210726_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
