# Generated by Django 3.2.5 on 2021-07-27 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0008_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('date_made', models.DateTimeField(auto_now_add=True)),
                ('appointment_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
