# Generated by Django 3.2.5 on 2021-07-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0011_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthealthhistory',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, default='2021-07-28 00:10:25.142087+03'),
            preserve_default=False,
        ),
    ]
