# Generated by Django 3.2.5 on 2021-07-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0012_patienthealthhistory_date_recorded'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dose',
            field=models.CharField(default='2*3', max_length=30),
            preserve_default=False,
        ),
    ]
