# Generated by Django 3.2.5 on 2021-07-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0013_prescription_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2021-07-27 22:58:51.049087+03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(default='Medicine'),
            preserve_default=False,
        ),
    ]
